#!/usr/bin/python
import datetime

clocks = {
    0: "🕛", 
    1: "🕐",
    2: "🕑",
    3: "🕒",
    4: "🕓",
    5: "🕔",
    6: "🕕",
    7: "🕖",
    8: "🕗",
    9: "🕘",
    10: "🕙",
    11: "🕚"
}

hour = datetime.datetime.now().hour
print(clocks[hour%12])
