#!/usr/bin/python3
import argparse
import os


AVAILABLE_APPS_FILE = f"/home/{os.getenv('USER')}/.webapps"
CHROME_DEFAULT = 'google-chrome' in os.getenv('BROWSER', '')
APP_MODE_FLAG = os.getenv('GOOGLEAPPMODE', '0')

if not os.path.exists(AVAILABLE_APPS_FILE):
    f = open(AVAILABLE_APPS_FILE, 'w+')
    f.close()

with open(AVAILABLE_APPS_FILE, 'r') as f:
    lines = [line.split() for line in f.readlines()]
apps = filter(lambda e: len(e) >= 2, lines)
AVAILABLE_APPS = {app[0]: app[1] for app in apps}


parser = argparse.ArgumentParser(
    description="runs specified web application in default browser."
)
parser.add_argument('appname', choices=AVAILABLE_APPS.keys(),
                    help="name of application to run")
parser.add_argument(
    '-a', '--app', action='store_true',
    help="run application in app mode. Requires Google Chrome browser " +
    "installed and set as default browser (variable BROWSER). " +
    "NOTE: app mode will be enabled also if GOOGLEAPPMODE is set to 1!"
)
parser.add_argument(
    '-b', '--browser', action='store_true',
    help="run application in new tab in browser. This is the default option " +
    "if Google Chrome is not set as default browser (variable BROWSER)"
)
args = parser.parse_args()


app_mode = False
if args.app and args.browser or (not args.app and not args.browser):
    app_mode = APP_MODE_FLAG == '1' and CHROME_DEFAULT
elif args.app and CHROME_DEFAULT:
    app_mode = True

if app_mode:
    cmd = f'$BROWSER --app="{AVAILABLE_APPS[args.appname]}"'
else:
    cmd = f'$BROWSER "{AVAILABLE_APPS[args.appname]}"'

os.system(cmd)
