#!/usr/bin/python3
import argparse
import os

AVAILABLE_APPS = {
    'calendar':     "https://calendar.google.com",
    'colaboratory': "https://colab.research.google.com",
    'contacts':     "https://contacts.google.com",
    'drive':        "https://drive.google.com",
    'mail':         "https://mail.google.com",
    'maps':         "https://maps.google.com",
    'news':         "https://news.google.com",
    'photos':       "https://photos.google.com",
    'play':         "https://play.google.com",
    'search':       "https://google.com",
    'translate':    "https://translate.google.com",
    'youtube':      "https://youtube.com"
}
    

parser = argparse.ArgumentParser(
    description="runs google application in default browser."
)
parser.add_argument('appname', choices=AVAILABLE_APPS.keys(),
                    help="name of application to run")
parser.add_argument(
    '-a', '--app', action='store_true',
    help="run application in app mode. Requires Google Chrome browser " +
    "installed and set as default browser (variable BROWSER). " +
    "NOTE: app mode will be enabled also if GOOGLEAPPMODE is set to 1!"
)
parser.add_argument(
    '-b', '--browser', action='store_true',
    help="run application in new tab in browser. This is the default option " +
    "if Google Chrome is not set as default browser (variable BROWSER)"
)
args = parser.parse_args()

chrome_default = 'google-chrome' in os.getenv('BROWSER', '')
app_mode_flag = os.getenv('GOOGLEAPPMODE', '0')
with open('/home/norbert/googleappmode.txt', '+w') as f:
    f.write(str(app_mode_flag))
    f.write(os.getenv('BROWSER'))

app_mode = False
if args.app and args.browser or (not args.app and not args.browser):
    app_mode = app_mode_flag == '1' and chrome_default
elif args.app and chrome_default:
    app_mode = True

if app_mode:
    cmd = f'$BROWSER --app="{AVAILABLE_APPS[args.appname]}"'
else:
    cmd = f'$BROWSER "{AVAILABLE_APPS[args.appname]}"'

os.system(cmd)
